services:

  database:
    build: ./database # Postgresql
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    # networks:
    #   - db

  generationapi:
    build:
      context: ./generation
      args:
        - GITHUB_DOCKIT_TOKEN=${GITHUB_DOCKIT_TOKEN}
    ports:
      - 8081:8080

volumes:
  pgdata:

# networks:
#   db:
