services:

  database:

    image: 'postgres:alpine'

    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'jsot'

    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
