<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="DocumentFormat.OpenXml" Version="3.3.0" />
      <PackageReference Include="SkiaSharp" Version="3.119.2-preview.1" />
      <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="3.119.2-preview.1" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="SearchReplaceEngine\" />
      <Folder Include="TemplateEngine\" />
    </ItemGroup>

</Project>
